languageCode = "en-US"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "tubenhirn.com"
copyright = "2023 © Johannes Stang. All Right Reserved."

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
  name = "Johannes Stang"
  image = "img/jstang2.png"
  # headline = "I'm only human"
  bio = "Squeeze my brain and develop things."
  links = [
    { github = "https://github.com/tubenhirn" },
    { gitlab = "https://gitlab.com/jstang" },
    { mastodon = "https://hachyderm.io/@tubenhirn" },
   ]
