baseURL = 'https://tubenhirn.com/'
languageCode = 'en-us'
title = 'tubenhirn.com'
author = 'Johannes Stang'
description = 'developer'
avatar = 'path/to/avatar.png'
menu_item_separator = '-'
favicon = '/favicon.ico'

theme = "m10c"
